# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0009_auto_20190122_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'Like'), ('d', 'Dislike'), ('u', 'Undecided')], default='u', max_length=2),
        ),
    ]
