# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-22 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0010_auto_20190122_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdog',
            old_name='status',
            new_name='decision',
        ),
    ]
