# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0012_auto_20190122_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_group',
            field=models.CharField(default='b', max_length=1),
        ),
    ]
